spring.application.name=demo

security.jwt.secret-key=dGhpcyBpcyBzZWNyZXQga2V5IGZvciB0b2tlbiBiYXNlZCBhdXRoZW50aWNhdGlvbg==
security.jwt.expiration=86400000

# ============================================== database config =======================================================
spring.datasource.url=jdbc:postgresql://localhost:5430/expensedb
spring.datasource.username=expense
spring.datasource.password=expense

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ============================================= connection pool config =================================================
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=2000000
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=15

# ================================================ jackson config ======================================================
spring.jackson.serialization.indent-output=true
spring.jackson.default-property-inclusion=non_null
#spring.jackson.property-naming-strategy=SNAKE_CASE
